### ISSUE TITLE
No longer removes serial number?

### ISSUE THREAD

**Issue by LordPinkerton** [Scandal-UK/Incognito_RCM#4]
After using this version, am I correct in assuming that this no longer removes the serial number but rather changes it to a XAW00000000001?

**Comment by Scandal-UK** [comment]
All previous versions also set the serial number to XAW00000000001;
https://github.com/jimzrt/Incognito_RCM/blob/b76177098972599139f3ef33c5aa2d7220c77b57/source/incognito/incognito.c#L326-L339

However, it did not previously show in the Nintendo menu because the older version did not update the checksums.
